#!/bin/bash

# docker-compose down will remove all external storages of the container instances
# only execute this if you truly would like to remove all data generated by kafka
# e.g. all streaming data, all consumer positions, etc
#docker-compose down

# create docker network to ease local testing
docker network create kafka_net_cfg

docker-compose stop
#docker-compose up --build --force-recreate -d
docker-compose up --build -d
